python3 get_bins.py 'airplane'
python3 get_bins.py 'alarm clock'
python3 get_bins.py 'ambulance'
python3 get_bins.py 'angel'
python3 get_bins.py 'animal migration'
python3 get_bins.py 'ant'
python3 get_bins.py 'anvil'
python3 get_bins.py 'apple'
python3 get_bins.py 'arm'
python3 get_bins.py 'asparagus'
python3 get_bins.py 'axe'
python3 get_bins.py 'backpack'
python3 get_bins.py 'banana'
python3 get_bins.py 'bandage'
python3 get_bins.py 'barn'
python3 get_bins.py 'baseball bat'
python3 get_bins.py 'baseball'
python3 get_bins.py 'basket'
python3 get_bins.py 'basketball'
python3 get_bins.py 'bat'
python3 get_bins.py 'bathtub'
python3 get_bins.py 'beach'
python3 get_bins.py 'bear'
python3 get_bins.py 'beard'
python3 get_bins.py 'bed'
python3 get_bins.py 'bee'
python3 get_bins.py 'belt'
python3 get_bins.py 'bench'
python3 get_bins.py 'bicycle'
python3 get_bins.py 'binoculars'
python3 get_bins.py 'bird'
python3 get_bins.py 'birthday cake'
python3 get_bins.py 'blackberry'
python3 get_bins.py 'blueberry'
python3 get_bins.py 'book'
python3 get_bins.py 'boomerang'
python3 get_bins.py 'bottlecap'
python3 get_bins.py 'bowtie'
python3 get_bins.py 'bracelet'
python3 get_bins.py 'brain'
python3 get_bins.py 'bread'
python3 get_bins.py 'bridge'
python3 get_bins.py 'broccoli'
python3 get_bins.py 'broom'
python3 get_bins.py 'bucket'
python3 get_bins.py 'bulldozer'
python3 get_bins.py 'bus'
python3 get_bins.py 'bush'
python3 get_bins.py 'butterfly'
python3 get_bins.py 'cactus'
python3 get_bins.py 'cake'
python3 get_bins.py 'calculator'
python3 get_bins.py 'calendar'
python3 get_bins.py 'camel'
python3 get_bins.py 'camera'
python3 get_bins.py 'camouflage'
python3 get_bins.py 'campfire'
python3 get_bins.py 'candle'
python3 get_bins.py 'cannon'
python3 get_bins.py 'canoe'
python3 get_bins.py 'car'
python3 get_bins.py 'carrot'
python3 get_bins.py 'castle'
python3 get_bins.py 'cat'
python3 get_bins.py 'ceiling fan'
python3 get_bins.py 'cell phone'
python3 get_bins.py 'cello'
python3 get_bins.py 'chair'
python3 get_bins.py 'chandelier'
python3 get_bins.py 'church'
python3 get_bins.py 'circle'
python3 get_bins.py 'clarinet'
python3 get_bins.py 'clock'
python3 get_bins.py 'cloud'
python3 get_bins.py 'coffee cup'
python3 get_bins.py 'compass'
python3 get_bins.py 'computer'
python3 get_bins.py 'cookie'
python3 get_bins.py 'cooler'
python3 get_bins.py 'couch'
python3 get_bins.py 'cow'
python3 get_bins.py 'crab'
python3 get_bins.py 'crayon'
python3 get_bins.py 'crocodile'
python3 get_bins.py 'crown'
python3 get_bins.py 'cruise ship'
python3 get_bins.py 'cup'
python3 get_bins.py 'diamond'
python3 get_bins.py 'dishwasher'
python3 get_bins.py 'diving board'
python3 get_bins.py 'dog'
python3 get_bins.py 'dolphin'
python3 get_bins.py 'donut'
python3 get_bins.py 'door'
python3 get_bins.py 'dragon'
python3 get_bins.py 'dresser'
python3 get_bins.py 'drill'
python3 get_bins.py 'drums'
python3 get_bins.py 'duck'
python3 get_bins.py 'dumbbell'
python3 get_bins.py 'ear'
python3 get_bins.py 'elbow'
python3 get_bins.py 'elephant'
python3 get_bins.py 'envelope'
python3 get_bins.py 'eraser'
python3 get_bins.py 'eye'
python3 get_bins.py 'eyeglasses'
python3 get_bins.py 'face'
python3 get_bins.py 'fan'
python3 get_bins.py 'feather'
python3 get_bins.py 'fence'
python3 get_bins.py 'finger'
python3 get_bins.py 'fire hydrant'
python3 get_bins.py 'fireplace'
python3 get_bins.py 'firetruck'
python3 get_bins.py 'fish'
python3 get_bins.py 'flamingo'
python3 get_bins.py 'flashlight'
python3 get_bins.py 'flip flops'
python3 get_bins.py 'floor lamp'
python3 get_bins.py 'flower'
python3 get_bins.py 'flying saucer'
python3 get_bins.py 'foot'
python3 get_bins.py 'fork'
python3 get_bins.py 'frog'
python3 get_bins.py 'frying pan'
python3 get_bins.py 'garden hose'
python3 get_bins.py 'garden'
python3 get_bins.py 'giraffe'
python3 get_bins.py 'goatee'
python3 get_bins.py 'golf club'
python3 get_bins.py 'grapes'
python3 get_bins.py 'grass'
python3 get_bins.py 'guitar'
python3 get_bins.py 'hamburger'
python3 get_bins.py 'hammer'
python3 get_bins.py 'hand'
python3 get_bins.py 'harp'
python3 get_bins.py 'hat'
python3 get_bins.py 'headphones'
python3 get_bins.py 'hedgehog'
python3 get_bins.py 'helicopter'
python3 get_bins.py 'helmet'
python3 get_bins.py 'hexagon'
python3 get_bins.py 'hockey puck'
python3 get_bins.py 'hockey stick'
python3 get_bins.py 'horse'
python3 get_bins.py 'hospital'
python3 get_bins.py 'hot air balloon'
python3 get_bins.py 'hot dog'
python3 get_bins.py 'hot tub'
python3 get_bins.py 'hourglass'
python3 get_bins.py 'house plant'
python3 get_bins.py 'house'
python3 get_bins.py 'hurricane'
python3 get_bins.py 'ice cream'
python3 get_bins.py 'jacket'
python3 get_bins.py 'jail'
python3 get_bins.py 'kangaroo'
python3 get_bins.py 'key'
python3 get_bins.py 'keyboard'
python3 get_bins.py 'knee'
python3 get_bins.py 'knife'
python3 get_bins.py 'ladder'
python3 get_bins.py 'lantern'
python3 get_bins.py 'laptop'
python3 get_bins.py 'leaf'
python3 get_bins.py 'leg'
python3 get_bins.py 'light bulb'
python3 get_bins.py 'lighter'
python3 get_bins.py 'lighthouse'
python3 get_bins.py 'lightning'
python3 get_bins.py 'line'
python3 get_bins.py 'lion'
python3 get_bins.py 'lipstick'
python3 get_bins.py 'lobster'
python3 get_bins.py 'lollipop'
python3 get_bins.py 'mailbox'
python3 get_bins.py 'map'
python3 get_bins.py 'marker'
python3 get_bins.py 'matches'
python3 get_bins.py 'megaphone'
python3 get_bins.py 'mermaid'
python3 get_bins.py 'microphone'
python3 get_bins.py 'microwave'
python3 get_bins.py 'monkey'
python3 get_bins.py 'moon'
python3 get_bins.py 'mosquito'
python3 get_bins.py 'motorbike'
python3 get_bins.py 'mountain'
python3 get_bins.py 'mouse'
python3 get_bins.py 'moustache'
python3 get_bins.py 'mouth'
python3 get_bins.py 'mug'
python3 get_bins.py 'mushroom'
python3 get_bins.py 'nail'
python3 get_bins.py 'necklace'
python3 get_bins.py 'nose'
python3 get_bins.py 'ocean'
python3 get_bins.py 'octagon'
python3 get_bins.py 'octopus'
python3 get_bins.py 'onion'
python3 get_bins.py 'oven'
python3 get_bins.py 'owl'
python3 get_bins.py 'paint can'
python3 get_bins.py 'paintbrush'
python3 get_bins.py 'palm tree'
python3 get_bins.py 'panda'
python3 get_bins.py 'pants'
python3 get_bins.py 'paper clip'
python3 get_bins.py 'parachute'
python3 get_bins.py 'parrot'
python3 get_bins.py 'passport'
python3 get_bins.py 'peanut'
python3 get_bins.py 'pear'
python3 get_bins.py 'peas'
python3 get_bins.py 'pencil'
python3 get_bins.py 'penguin'
python3 get_bins.py 'piano'
python3 get_bins.py 'pickup truck'
python3 get_bins.py 'picture frame'
python3 get_bins.py 'pig'
python3 get_bins.py 'pillow'
python3 get_bins.py 'pineapple'
python3 get_bins.py 'pizza'
python3 get_bins.py 'pliers'
python3 get_bins.py 'police car'
python3 get_bins.py 'pond'
python3 get_bins.py 'pool'
python3 get_bins.py 'popsicle'
python3 get_bins.py 'postcard'
python3 get_bins.py 'potato'
python3 get_bins.py 'power outlet'
python3 get_bins.py 'purse'
python3 get_bins.py 'rabbit'
python3 get_bins.py 'raccoon'
python3 get_bins.py 'radio'
python3 get_bins.py 'rain'
python3 get_bins.py 'rainbow'
python3 get_bins.py 'rake'
python3 get_bins.py 'remote control'
python3 get_bins.py 'rhinoceros'
python3 get_bins.py 'rifle'
python3 get_bins.py 'river'
python3 get_bins.py 'roller coaster'
python3 get_bins.py 'rollerskates'
python3 get_bins.py 'sailboat'
python3 get_bins.py 'sandwich'
python3 get_bins.py 'saw'
python3 get_bins.py 'saxophone'
python3 get_bins.py 'school bus'
python3 get_bins.py 'scissors'
python3 get_bins.py 'scorpion'
python3 get_bins.py 'screwdriver'
python3 get_bins.py 'sea turtle'
python3 get_bins.py 'see saw'
python3 get_bins.py 'shark'
python3 get_bins.py 'sheep'
python3 get_bins.py 'shoe'
python3 get_bins.py 'shorts'
python3 get_bins.py 'shovel'
python3 get_bins.py 'sink'
python3 get_bins.py 'skateboard'
python3 get_bins.py 'skull'
python3 get_bins.py 'skyscraper'
python3 get_bins.py 'sleeping bag'
python3 get_bins.py 'smiley face'
python3 get_bins.py 'snail'
python3 get_bins.py 'snake'
python3 get_bins.py 'snorkel'
python3 get_bins.py 'snowflake'
python3 get_bins.py 'snowman'
python3 get_bins.py 'soccer ball'
python3 get_bins.py 'sock'
python3 get_bins.py 'speedboat'
python3 get_bins.py 'spider'
python3 get_bins.py 'spoon'
python3 get_bins.py 'spreadsheet'
python3 get_bins.py 'square'
python3 get_bins.py 'squiggle'
python3 get_bins.py 'squirrel'
python3 get_bins.py 'stairs'
python3 get_bins.py 'star'
python3 get_bins.py 'steak'
python3 get_bins.py 'stereo'
python3 get_bins.py 'stethoscope'
python3 get_bins.py 'stitches'
python3 get_bins.py 'stop sign'
python3 get_bins.py 'stove'
python3 get_bins.py 'strawberry'
python3 get_bins.py 'streetlight'
python3 get_bins.py 'string bean'
python3 get_bins.py 'submarine'
python3 get_bins.py 'suitcase'
python3 get_bins.py 'sun'
python3 get_bins.py 'swan'
python3 get_bins.py 'sweater'
python3 get_bins.py 'swing set'
python3 get_bins.py 'sword'
python3 get_bins.py 'syringe'
python3 get_bins.py 't-shirt'
python3 get_bins.py 'table'
python3 get_bins.py 'teapot'
python3 get_bins.py 'teddy-bear'
python3 get_bins.py 'telephone'
python3 get_bins.py 'television'
python3 get_bins.py 'tennis racquet'
python3 get_bins.py 'tent'
python3 get_bins.py 'tiger'
python3 get_bins.py 'toaster'
python3 get_bins.py 'toe'
python3 get_bins.py 'toilet'
python3 get_bins.py 'tooth'
python3 get_bins.py 'toothbrush'
python3 get_bins.py 'toothpaste'
python3 get_bins.py 'tornado'
python3 get_bins.py 'tractor'
python3 get_bins.py 'traffic light'
python3 get_bins.py 'train'
python3 get_bins.py 'tree'
python3 get_bins.py 'triangle'
python3 get_bins.py 'trombone'
python3 get_bins.py 'truck'
python3 get_bins.py 'trumpet'
python3 get_bins.py 'umbrella'
python3 get_bins.py 'underwear'
python3 get_bins.py 'van'
python3 get_bins.py 'vase'
python3 get_bins.py 'violin'
python3 get_bins.py 'washing machine'
python3 get_bins.py 'watermelon'
python3 get_bins.py 'waterslide'
python3 get_bins.py 'whale'
python3 get_bins.py 'wheel'
python3 get_bins.py 'windmill'
python3 get_bins.py 'wine bottle'
python3 get_bins.py 'wine glass'
python3 get_bins.py 'wristwatch'
python3 get_bins.py 'yoga'
python3 get_bins.py 'zebra'
python3 get_bins.py 'zigzag'

