pypy make_thumbs.py -n 500 bdata/ant.bin
pypy make_thumbs.py -n 500 bdata/bat.bin
pypy make_thumbs.py -n 500 bdata/bear.bin
pypy make_thumbs.py -n 500 bdata/bee.bin
pypy make_thumbs.py -n 500 bdata/bird.bin
pypy make_thumbs.py -n 500 bdata/butterfly.bin
pypy make_thumbs.py -n 500 bdata/camel.bin
pypy make_thumbs.py -n 500 bdata/cat.bin
pypy make_thumbs.py -n 500 bdata/cow.bin
pypy make_thumbs.py -n 500 bdata/crab.bin
pypy make_thumbs.py -n 500 bdata/dog.bin
pypy make_thumbs.py -n 500 bdata/dolphin.bin
pypy make_thumbs.py -n 500 bdata/dragon.bin
pypy make_thumbs.py -n 500 bdata/duck.bin
pypy make_thumbs.py -n 500 bdata/elephant.bin
pypy make_thumbs.py -n 500 bdata/fish.bin
pypy make_thumbs.py -n 500 bdata/flamingo.bin
pypy make_thumbs.py -n 500 bdata/frog.bin
pypy make_thumbs.py -n 500 bdata/giraffe.bin
pypy make_thumbs.py -n 500 bdata/hedgehog.bin
pypy make_thumbs.py -n 500 bdata/horse.bin
pypy make_thumbs.py -n 500 bdata/kangaroo.bin
pypy make_thumbs.py -n 500 bdata/lion.bin
pypy make_thumbs.py -n 500 bdata/lobster.bin
pypy make_thumbs.py -n 500 bdata/monkey.bin
pypy make_thumbs.py -n 500 bdata/mouse.bin
pypy make_thumbs.py -n 500 bdata/octopus.bin
pypy make_thumbs.py -n 500 bdata/owl.bin
pypy make_thumbs.py -n 500 bdata/panda.bin
pypy make_thumbs.py -n 500 bdata/parrot.bin
pypy make_thumbs.py -n 500 bdata/penguin.bin
pypy make_thumbs.py -n 500 bdata/pig.bin
pypy make_thumbs.py -n 500 bdata/rabbit.bin
pypy make_thumbs.py -n 500 bdata/raccoon.bin
pypy make_thumbs.py -n 500 bdata/rhinoceros.bin
pypy make_thumbs.py -n 500 bdata/scorpion.bin
pypy make_thumbs.py -n 500 bdata/sea_turtle.bin
pypy make_thumbs.py -n 500 bdata/shark.bin
pypy make_thumbs.py -n 500 bdata/sheep.bin
pypy make_thumbs.py -n 500 bdata/snail.bin
pypy make_thumbs.py -n 500 bdata/snake.bin
pypy make_thumbs.py -n 500 bdata/spider.bin
pypy make_thumbs.py -n 500 bdata/squirrel.bin
pypy make_thumbs.py -n 500 bdata/swan.bin
pypy make_thumbs.py -n 500 bdata/tiger.bin
pypy make_thumbs.py -n 500 bdata/whale.bin 
pypy make_thumbs.py -n 500 bdata/zebra.bin
# ant bat bear bee bird butterfly camel cat cow crab dog dolphin dragon duck elephant fish flamingo frog giraffe hedgehog horse kangaroo lion lobster monkey mouse octopus owl panda parrot penguin pig rabbit raccoon rhinoceros scorpion sea_turtle shark sheep snail snake spider squirrel swan tiger whale zebra
pypy mix_thumbs.py -n 500 -o thumbs/animals.txt ant bat bear bee bird butterfly camel cat cow crab dog dolphin dragon duck elephant fish flamingo frog giraffe hedgehog horse kangaroo lion lobster monkey mouse octopus owl panda parrot penguin pig rabbit raccoon rhinoceros scorpion sea_turtle shark sheep snail snake spider squirrel swan tiger whale zebra
