# (use pypy or something faster if you can)
python3 make_thumbs.py -n 500 bdata/airplane.bin
python3 make_thumbs.py -n 500 bdata/alarm_clock.bin
python3 make_thumbs.py -n 500 bdata/ambulance.bin
python3 make_thumbs.py -n 500 bdata/angel.bin
python3 make_thumbs.py -n 500 bdata/animal_migration.bin
python3 make_thumbs.py -n 500 bdata/ant.bin
python3 make_thumbs.py -n 500 bdata/anvil.bin
python3 make_thumbs.py -n 500 bdata/apple.bin
python3 make_thumbs.py -n 500 bdata/arm.bin
python3 make_thumbs.py -n 500 bdata/asparagus.bin
python3 make_thumbs.py -n 500 bdata/axe.bin
python3 make_thumbs.py -n 500 bdata/backpack.bin
python3 make_thumbs.py -n 500 bdata/banana.bin
python3 make_thumbs.py -n 500 bdata/bandage.bin
python3 make_thumbs.py -n 500 bdata/barn.bin
python3 make_thumbs.py -n 500 bdata/baseball_bat.bin
python3 make_thumbs.py -n 500 bdata/baseball.bin
python3 make_thumbs.py -n 500 bdata/basket.bin
python3 make_thumbs.py -n 500 bdata/basketball.bin
python3 make_thumbs.py -n 500 bdata/bat.bin
python3 make_thumbs.py -n 500 bdata/bathtub.bin
python3 make_thumbs.py -n 500 bdata/beach.bin
python3 make_thumbs.py -n 500 bdata/bear.bin
python3 make_thumbs.py -n 500 bdata/beard.bin
python3 make_thumbs.py -n 500 bdata/bed.bin
python3 make_thumbs.py -n 500 bdata/bee.bin
python3 make_thumbs.py -n 500 bdata/belt.bin
python3 make_thumbs.py -n 500 bdata/bench.bin
python3 make_thumbs.py -n 500 bdata/bicycle.bin
python3 make_thumbs.py -n 500 bdata/binoculars.bin
python3 make_thumbs.py -n 500 bdata/bird.bin
python3 make_thumbs.py -n 500 bdata/birthday_cake.bin
python3 make_thumbs.py -n 500 bdata/blackberry.bin
python3 make_thumbs.py -n 500 bdata/blueberry.bin
python3 make_thumbs.py -n 500 bdata/book.bin
python3 make_thumbs.py -n 500 bdata/boomerang.bin
python3 make_thumbs.py -n 500 bdata/bottlecap.bin
python3 make_thumbs.py -n 500 bdata/bowtie.bin
python3 make_thumbs.py -n 500 bdata/bracelet.bin
python3 make_thumbs.py -n 500 bdata/brain.bin
python3 make_thumbs.py -n 500 bdata/bread.bin
python3 make_thumbs.py -n 500 bdata/bridge.bin
python3 make_thumbs.py -n 500 bdata/broccoli.bin
python3 make_thumbs.py -n 500 bdata/broom.bin
python3 make_thumbs.py -n 500 bdata/bucket.bin
python3 make_thumbs.py -n 500 bdata/bulldozer.bin
python3 make_thumbs.py -n 500 bdata/bus.bin
python3 make_thumbs.py -n 500 bdata/bush.bin
python3 make_thumbs.py -n 500 bdata/butterfly.bin
python3 make_thumbs.py -n 500 bdata/cactus.bin
python3 make_thumbs.py -n 500 bdata/cake.bin
python3 make_thumbs.py -n 500 bdata/calculator.bin
python3 make_thumbs.py -n 500 bdata/calendar.bin
python3 make_thumbs.py -n 500 bdata/camel.bin
python3 make_thumbs.py -n 500 bdata/camera.bin
python3 make_thumbs.py -n 500 bdata/camouflage.bin
python3 make_thumbs.py -n 500 bdata/campfire.bin
python3 make_thumbs.py -n 500 bdata/candle.bin
python3 make_thumbs.py -n 500 bdata/cannon.bin
python3 make_thumbs.py -n 500 bdata/canoe.bin
python3 make_thumbs.py -n 500 bdata/car.bin
python3 make_thumbs.py -n 500 bdata/carrot.bin
python3 make_thumbs.py -n 500 bdata/castle.bin
python3 make_thumbs.py -n 500 bdata/cat.bin
python3 make_thumbs.py -n 500 bdata/ceiling_fan.bin
python3 make_thumbs.py -n 500 bdata/cell_phone.bin
python3 make_thumbs.py -n 500 bdata/cello.bin
python3 make_thumbs.py -n 500 bdata/chair.bin
python3 make_thumbs.py -n 500 bdata/chandelier.bin
python3 make_thumbs.py -n 500 bdata/church.bin
python3 make_thumbs.py -n 500 bdata/circle.bin
python3 make_thumbs.py -n 500 bdata/clarinet.bin
python3 make_thumbs.py -n 500 bdata/clock.bin
python3 make_thumbs.py -n 500 bdata/cloud.bin
python3 make_thumbs.py -n 500 bdata/coffee_cup.bin
python3 make_thumbs.py -n 500 bdata/compass.bin
python3 make_thumbs.py -n 500 bdata/computer.bin
python3 make_thumbs.py -n 500 bdata/cookie.bin
python3 make_thumbs.py -n 500 bdata/cooler.bin
python3 make_thumbs.py -n 500 bdata/couch.bin
python3 make_thumbs.py -n 500 bdata/cow.bin
python3 make_thumbs.py -n 500 bdata/crab.bin
python3 make_thumbs.py -n 500 bdata/crayon.bin
python3 make_thumbs.py -n 500 bdata/crocodile.bin
python3 make_thumbs.py -n 500 bdata/crown.bin
python3 make_thumbs.py -n 500 bdata/cruise_ship.bin
python3 make_thumbs.py -n 500 bdata/cup.bin
python3 make_thumbs.py -n 500 bdata/diamond.bin
python3 make_thumbs.py -n 500 bdata/dishwasher.bin
python3 make_thumbs.py -n 500 bdata/diving_board.bin
python3 make_thumbs.py -n 500 bdata/dog.bin
python3 make_thumbs.py -n 500 bdata/dolphin.bin
python3 make_thumbs.py -n 500 bdata/donut.bin
python3 make_thumbs.py -n 500 bdata/door.bin
python3 make_thumbs.py -n 500 bdata/dragon.bin
python3 make_thumbs.py -n 500 bdata/dresser.bin
python3 make_thumbs.py -n 500 bdata/drill.bin
python3 make_thumbs.py -n 500 bdata/drums.bin
python3 make_thumbs.py -n 500 bdata/duck.bin
python3 make_thumbs.py -n 500 bdata/dumbbell.bin
python3 make_thumbs.py -n 500 bdata/ear.bin
python3 make_thumbs.py -n 500 bdata/elbow.bin
python3 make_thumbs.py -n 500 bdata/elephant.bin
python3 make_thumbs.py -n 500 bdata/envelope.bin
python3 make_thumbs.py -n 500 bdata/eraser.bin
python3 make_thumbs.py -n 500 bdata/eye.bin
python3 make_thumbs.py -n 500 bdata/eyeglasses.bin
python3 make_thumbs.py -n 500 bdata/face.bin
python3 make_thumbs.py -n 500 bdata/fan.bin
python3 make_thumbs.py -n 500 bdata/feather.bin
python3 make_thumbs.py -n 500 bdata/fence.bin
python3 make_thumbs.py -n 500 bdata/finger.bin
python3 make_thumbs.py -n 500 bdata/fire_hydrant.bin
python3 make_thumbs.py -n 500 bdata/fireplace.bin
python3 make_thumbs.py -n 500 bdata/firetruck.bin
python3 make_thumbs.py -n 500 bdata/fish.bin
python3 make_thumbs.py -n 500 bdata/flamingo.bin
python3 make_thumbs.py -n 500 bdata/flashlight.bin
python3 make_thumbs.py -n 500 bdata/flip_flops.bin
python3 make_thumbs.py -n 500 bdata/floor_lamp.bin
python3 make_thumbs.py -n 500 bdata/flower.bin
python3 make_thumbs.py -n 500 bdata/flying_saucer.bin
python3 make_thumbs.py -n 500 bdata/foot.bin
python3 make_thumbs.py -n 500 bdata/fork.bin
python3 make_thumbs.py -n 500 bdata/frog.bin
python3 make_thumbs.py -n 500 bdata/frying_pan.bin
python3 make_thumbs.py -n 500 bdata/garden_hose.bin
python3 make_thumbs.py -n 500 bdata/garden.bin
python3 make_thumbs.py -n 500 bdata/giraffe.bin
python3 make_thumbs.py -n 500 bdata/goatee.bin
python3 make_thumbs.py -n 500 bdata/golf_club.bin
python3 make_thumbs.py -n 500 bdata/grapes.bin
python3 make_thumbs.py -n 500 bdata/grass.bin
python3 make_thumbs.py -n 500 bdata/guitar.bin
python3 make_thumbs.py -n 500 bdata/hamburger.bin
python3 make_thumbs.py -n 500 bdata/hammer.bin
python3 make_thumbs.py -n 500 bdata/hand.bin
python3 make_thumbs.py -n 500 bdata/harp.bin
python3 make_thumbs.py -n 500 bdata/hat.bin
python3 make_thumbs.py -n 500 bdata/headphones.bin
python3 make_thumbs.py -n 500 bdata/hedgehog.bin
python3 make_thumbs.py -n 500 bdata/helicopter.bin
python3 make_thumbs.py -n 500 bdata/helmet.bin
python3 make_thumbs.py -n 500 bdata/hexagon.bin
python3 make_thumbs.py -n 500 bdata/hockey_puck.bin
python3 make_thumbs.py -n 500 bdata/hockey_stick.bin
python3 make_thumbs.py -n 500 bdata/horse.bin
python3 make_thumbs.py -n 500 bdata/hospital.bin
python3 make_thumbs.py -n 500 bdata/hot_air_balloon.bin
python3 make_thumbs.py -n 500 bdata/hot_dog.bin
python3 make_thumbs.py -n 500 bdata/hot_tub.bin
python3 make_thumbs.py -n 500 bdata/hourglass.bin
python3 make_thumbs.py -n 500 bdata/house_plant.bin
python3 make_thumbs.py -n 500 bdata/house.bin
python3 make_thumbs.py -n 500 bdata/hurricane.bin
python3 make_thumbs.py -n 500 bdata/ice_cream.bin
python3 make_thumbs.py -n 500 bdata/jacket.bin
python3 make_thumbs.py -n 500 bdata/jail.bin
python3 make_thumbs.py -n 500 bdata/kangaroo.bin
python3 make_thumbs.py -n 500 bdata/key.bin
python3 make_thumbs.py -n 500 bdata/keyboard.bin
python3 make_thumbs.py -n 500 bdata/knee.bin
python3 make_thumbs.py -n 500 bdata/knife.bin
python3 make_thumbs.py -n 500 bdata/ladder.bin
python3 make_thumbs.py -n 500 bdata/lantern.bin
python3 make_thumbs.py -n 500 bdata/laptop.bin
python3 make_thumbs.py -n 500 bdata/leaf.bin
python3 make_thumbs.py -n 500 bdata/leg.bin
python3 make_thumbs.py -n 500 bdata/light_bulb.bin
python3 make_thumbs.py -n 500 bdata/lighter.bin
python3 make_thumbs.py -n 500 bdata/lighthouse.bin
python3 make_thumbs.py -n 500 bdata/lightning.bin
python3 make_thumbs.py -n 500 bdata/line.bin
python3 make_thumbs.py -n 500 bdata/lion.bin
python3 make_thumbs.py -n 500 bdata/lipstick.bin
python3 make_thumbs.py -n 500 bdata/lobster.bin
python3 make_thumbs.py -n 500 bdata/lollipop.bin
python3 make_thumbs.py -n 500 bdata/mailbox.bin
python3 make_thumbs.py -n 500 bdata/map.bin
python3 make_thumbs.py -n 500 bdata/marker.bin
python3 make_thumbs.py -n 500 bdata/matches.bin
python3 make_thumbs.py -n 500 bdata/megaphone.bin
python3 make_thumbs.py -n 500 bdata/mermaid.bin
python3 make_thumbs.py -n 500 bdata/microphone.bin
python3 make_thumbs.py -n 500 bdata/microwave.bin
python3 make_thumbs.py -n 500 bdata/monkey.bin
python3 make_thumbs.py -n 500 bdata/moon.bin
python3 make_thumbs.py -n 500 bdata/mosquito.bin
python3 make_thumbs.py -n 500 bdata/motorbike.bin
python3 make_thumbs.py -n 500 bdata/mountain.bin
python3 make_thumbs.py -n 500 bdata/mouse.bin
python3 make_thumbs.py -n 500 bdata/moustache.bin
python3 make_thumbs.py -n 500 bdata/mouth.bin
python3 make_thumbs.py -n 500 bdata/mug.bin
python3 make_thumbs.py -n 500 bdata/mushroom.bin
python3 make_thumbs.py -n 500 bdata/nail.bin
python3 make_thumbs.py -n 500 bdata/necklace.bin
python3 make_thumbs.py -n 500 bdata/nose.bin
python3 make_thumbs.py -n 500 bdata/ocean.bin
python3 make_thumbs.py -n 500 bdata/octagon.bin
python3 make_thumbs.py -n 500 bdata/octopus.bin
python3 make_thumbs.py -n 500 bdata/onion.bin
python3 make_thumbs.py -n 500 bdata/oven.bin
python3 make_thumbs.py -n 500 bdata/owl.bin
python3 make_thumbs.py -n 500 bdata/paint_can.bin
python3 make_thumbs.py -n 500 bdata/paintbrush.bin
python3 make_thumbs.py -n 500 bdata/palm_tree.bin
python3 make_thumbs.py -n 500 bdata/panda.bin
python3 make_thumbs.py -n 500 bdata/pants.bin
python3 make_thumbs.py -n 500 bdata/paper_clip.bin
python3 make_thumbs.py -n 500 bdata/parachute.bin
python3 make_thumbs.py -n 500 bdata/parrot.bin
python3 make_thumbs.py -n 500 bdata/passport.bin
python3 make_thumbs.py -n 500 bdata/peanut.bin
python3 make_thumbs.py -n 500 bdata/pear.bin
python3 make_thumbs.py -n 500 bdata/peas.bin
python3 make_thumbs.py -n 500 bdata/pencil.bin
python3 make_thumbs.py -n 500 bdata/penguin.bin
python3 make_thumbs.py -n 500 bdata/piano.bin
python3 make_thumbs.py -n 500 bdata/pickup_truck.bin
python3 make_thumbs.py -n 500 bdata/picture_frame.bin
python3 make_thumbs.py -n 500 bdata/pig.bin
python3 make_thumbs.py -n 500 bdata/pillow.bin
python3 make_thumbs.py -n 500 bdata/pineapple.bin
python3 make_thumbs.py -n 500 bdata/pizza.bin
python3 make_thumbs.py -n 500 bdata/pliers.bin
python3 make_thumbs.py -n 500 bdata/police_car.bin
python3 make_thumbs.py -n 500 bdata/pond.bin
python3 make_thumbs.py -n 500 bdata/pool.bin
python3 make_thumbs.py -n 500 bdata/popsicle.bin
python3 make_thumbs.py -n 500 bdata/postcard.bin
python3 make_thumbs.py -n 500 bdata/potato.bin
python3 make_thumbs.py -n 500 bdata/power_outlet.bin
python3 make_thumbs.py -n 500 bdata/purse.bin
python3 make_thumbs.py -n 500 bdata/rabbit.bin
python3 make_thumbs.py -n 500 bdata/raccoon.bin
python3 make_thumbs.py -n 500 bdata/radio.bin
python3 make_thumbs.py -n 500 bdata/rain.bin
python3 make_thumbs.py -n 500 bdata/rainbow.bin
python3 make_thumbs.py -n 500 bdata/rake.bin
python3 make_thumbs.py -n 500 bdata/remote_control.bin
python3 make_thumbs.py -n 500 bdata/rhinoceros.bin
python3 make_thumbs.py -n 500 bdata/rifle.bin
python3 make_thumbs.py -n 500 bdata/river.bin
python3 make_thumbs.py -n 500 bdata/roller_coaster.bin
python3 make_thumbs.py -n 500 bdata/rollerskates.bin
python3 make_thumbs.py -n 500 bdata/sailboat.bin
python3 make_thumbs.py -n 500 bdata/sandwich.bin
python3 make_thumbs.py -n 500 bdata/saw.bin
python3 make_thumbs.py -n 500 bdata/saxophone.bin
python3 make_thumbs.py -n 500 bdata/school_bus.bin
python3 make_thumbs.py -n 500 bdata/scissors.bin
python3 make_thumbs.py -n 500 bdata/scorpion.bin
python3 make_thumbs.py -n 500 bdata/screwdriver.bin
python3 make_thumbs.py -n 500 bdata/sea_turtle.bin
python3 make_thumbs.py -n 500 bdata/see_saw.bin
python3 make_thumbs.py -n 500 bdata/shark.bin
python3 make_thumbs.py -n 500 bdata/sheep.bin
python3 make_thumbs.py -n 500 bdata/shoe.bin
python3 make_thumbs.py -n 500 bdata/shorts.bin
python3 make_thumbs.py -n 500 bdata/shovel.bin
python3 make_thumbs.py -n 500 bdata/sink.bin
python3 make_thumbs.py -n 500 bdata/skateboard.bin
python3 make_thumbs.py -n 500 bdata/skull.bin
python3 make_thumbs.py -n 500 bdata/skyscraper.bin
python3 make_thumbs.py -n 500 bdata/sleeping_bag.bin
python3 make_thumbs.py -n 500 bdata/smiley_face.bin
python3 make_thumbs.py -n 500 bdata/snail.bin
python3 make_thumbs.py -n 500 bdata/snake.bin
python3 make_thumbs.py -n 500 bdata/snorkel.bin
python3 make_thumbs.py -n 500 bdata/snowflake.bin
python3 make_thumbs.py -n 500 bdata/snowman.bin
python3 make_thumbs.py -n 500 bdata/soccer_ball.bin
python3 make_thumbs.py -n 500 bdata/sock.bin
python3 make_thumbs.py -n 500 bdata/speedboat.bin
python3 make_thumbs.py -n 500 bdata/spider.bin
python3 make_thumbs.py -n 500 bdata/spoon.bin
python3 make_thumbs.py -n 500 bdata/spreadsheet.bin
python3 make_thumbs.py -n 500 bdata/square.bin
python3 make_thumbs.py -n 500 bdata/squiggle.bin
python3 make_thumbs.py -n 500 bdata/squirrel.bin
python3 make_thumbs.py -n 500 bdata/stairs.bin
python3 make_thumbs.py -n 500 bdata/star.bin
python3 make_thumbs.py -n 500 bdata/steak.bin
python3 make_thumbs.py -n 500 bdata/stereo.bin
python3 make_thumbs.py -n 500 bdata/stethoscope.bin
python3 make_thumbs.py -n 500 bdata/stitches.bin
python3 make_thumbs.py -n 500 bdata/stop_sign.bin
python3 make_thumbs.py -n 500 bdata/stove.bin
python3 make_thumbs.py -n 500 bdata/strawberry.bin
python3 make_thumbs.py -n 500 bdata/streetlight.bin
python3 make_thumbs.py -n 500 bdata/string_bean.bin
python3 make_thumbs.py -n 500 bdata/submarine.bin
python3 make_thumbs.py -n 500 bdata/suitcase.bin
python3 make_thumbs.py -n 500 bdata/sun.bin
python3 make_thumbs.py -n 500 bdata/swan.bin
python3 make_thumbs.py -n 500 bdata/sweater.bin
python3 make_thumbs.py -n 500 bdata/swing_set.bin
python3 make_thumbs.py -n 500 bdata/sword.bin
python3 make_thumbs.py -n 500 bdata/syringe.bin
python3 make_thumbs.py -n 500 bdata/t-shirt.bin
python3 make_thumbs.py -n 500 bdata/table.bin
python3 make_thumbs.py -n 500 bdata/teapot.bin
python3 make_thumbs.py -n 500 bdata/teddy-bear.bin
python3 make_thumbs.py -n 500 bdata/telephone.bin
python3 make_thumbs.py -n 500 bdata/television.bin
python3 make_thumbs.py -n 500 bdata/tennis_racquet.bin
python3 make_thumbs.py -n 500 bdata/tent.bin
python3 make_thumbs.py -n 500 bdata/tiger.bin
python3 make_thumbs.py -n 500 bdata/toaster.bin
python3 make_thumbs.py -n 500 bdata/toe.bin
python3 make_thumbs.py -n 500 bdata/toilet.bin
python3 make_thumbs.py -n 500 bdata/tooth.bin
python3 make_thumbs.py -n 500 bdata/toothbrush.bin
python3 make_thumbs.py -n 500 bdata/toothpaste.bin
python3 make_thumbs.py -n 500 bdata/tornado.bin
python3 make_thumbs.py -n 500 bdata/tractor.bin
python3 make_thumbs.py -n 500 bdata/traffic_light.bin
python3 make_thumbs.py -n 500 bdata/train.bin
python3 make_thumbs.py -n 500 bdata/tree.bin
python3 make_thumbs.py -n 500 bdata/triangle.bin
python3 make_thumbs.py -n 500 bdata/trombone.bin
python3 make_thumbs.py -n 500 bdata/truck.bin
python3 make_thumbs.py -n 500 bdata/trumpet.bin
python3 make_thumbs.py -n 500 bdata/umbrella.bin
python3 make_thumbs.py -n 500 bdata/underwear.bin
python3 make_thumbs.py -n 500 bdata/van.bin
python3 make_thumbs.py -n 500 bdata/vase.bin
python3 make_thumbs.py -n 500 bdata/violin.bin
python3 make_thumbs.py -n 500 bdata/washing_machine.bin
python3 make_thumbs.py -n 500 bdata/watermelon.bin
python3 make_thumbs.py -n 500 bdata/waterslide.bin
python3 make_thumbs.py -n 500 bdata/whale.bin
python3 make_thumbs.py -n 500 bdata/wheel.bin
python3 make_thumbs.py -n 500 bdata/windmill.bin
python3 make_thumbs.py -n 500 bdata/wine_bottle.bin
python3 make_thumbs.py -n 500 bdata/wine_glass.bin
python3 make_thumbs.py -n 500 bdata/wristwatch.bin
python3 make_thumbs.py -n 500 bdata/yoga.bin
python3 make_thumbs.py -n 500 bdata/zebra.bin
python3 make_thumbs.py -n 500 bdata/zigzag.bin


# airplane alarm_clock ambulance angel animal_migration ant anvil apple arm asparagus axe backpack banana bandage barn baseball_bat baseball basket basketball bat bathtub beach bear beard bed bee belt bench bicycle binoculars bird birthday_cake blackberry blueberry book boomerang bottlecap bowtie bracelet brain bread bridge broccoli broom bucket bulldozer bus bush butterfly cactus cake calculator calendar camel camera camouflage campfire candle cannon canoe car carrot castle cat ceiling_fan cell_phone cello chair chandelier church circle clarinet clock cloud coffee_cup compass computer cookie cooler couch cow crab crayon crocodile crown cruise_ship cup diamond dishwasher diving_board dog dolphin donut door dragon dresser drill drums duck dumbbell ear elbow elephant envelope eraser eye eyeglasses face fan feather fence finger fire_hydrant fireplace firetruck fish flamingo flashlight flip_flops floor_lamp flower flying_saucer foot fork frog frying_pan garden_hose garden giraffe goatee golf_club grapes grass guitar hamburger hammer hand harp hat headphones hedgehog helicopter helmet hexagon hockey_puck hockey_stick horse hospital hot_air_balloon hot_dog hot_tub hourglass house_plant house hurricane ice_cream jacket jail kangaroo key keyboard knee knife ladder lantern laptop leaf leg light_bulb lighter lighthouse lightning line lion lipstick lobster lollipop mailbox map marker matches megaphone mermaid microphone microwave monkey moon mosquito motorbike mountain mouse moustache mouth mug mushroom nail necklace nose ocean octagon octopus onion oven owl paint_can paintbrush palm_tree panda pants paper_clip parachute parrot passport peanut pear peas pencil penguin piano pickup_truck picture_frame pig pillow pineapple pizza pliers police_car pond pool popsicle postcard potato power_outlet purse rabbit raccoon radio rain rainbow rake remote_control rhinoceros rifle river roller_coaster rollerskates sailboat sandwich saw saxophone school_bus scissors scorpion screwdriver sea_turtle see_saw shark sheep shoe shorts shovel sink skateboard skull skyscraper sleeping_bag smiley_face snail snake snorkel snowflake snowman soccer_ball sock speedboat spider spoon spreadsheet square squiggle squirrel stairs star steak stereo stethoscope stitches stop_sign stove strawberry streetlight string_bean submarine suitcase sun swan sweater swing_set sword syringe t-shirt table teapot teddy-bear telephone television tennis_racquet tent tiger toaster toe toilet tooth toothbrush toothpaste tornado tractor traffic_light train tree triangle trombone truck trumpet umbrella underwear van vase violin washing_machine watermelon waterslide whale wheel windmill wine_bottle wine_glass wristwatch yoga zebra zigzag 

#(use pypy or something faster if you can)
python3 mix_thumbs.py -n 500 -o thumbs/all.txt airplane alarm_clock ambulance angel animal_migration ant anvil apple arm asparagus axe backpack banana bandage barn baseball_bat baseball basket basketball bat bathtub beach bear beard bed bee belt bench bicycle binoculars bird birthday_cake blackberry blueberry book boomerang bottlecap bowtie bracelet brain bread bridge broccoli broom bucket bulldozer bus bush butterfly cactus cake calculator calendar camel camera camouflage campfire candle cannon canoe car carrot castle cat ceiling_fan cell_phone cello chair chandelier church circle clarinet clock cloud coffee_cup compass computer cookie cooler couch cow crab crayon crocodile crown cruise_ship cup diamond dishwasher diving_board dog dolphin donut door dragon dresser drill drums duck dumbbell ear elbow elephant envelope eraser eye eyeglasses face fan feather fence finger fire_hydrant fireplace firetruck fish flamingo flashlight flip_flops floor_lamp flower flying_saucer foot fork frog frying_pan garden_hose garden giraffe goatee golf_club grapes grass guitar hamburger hammer hand harp hat headphones hedgehog helicopter helmet hexagon hockey_puck hockey_stick horse hospital hot_air_balloon hot_dog hot_tub hourglass house_plant house hurricane ice_cream jacket jail kangaroo key keyboard knee knife ladder lantern laptop leaf leg light_bulb lighter lighthouse lightning line lion lipstick lobster lollipop mailbox map marker matches megaphone mermaid microphone microwave monkey moon mosquito motorbike mountain mouse moustache mouth mug mushroom nail necklace nose ocean octagon octopus onion oven owl paint_can paintbrush palm_tree panda pants paper_clip parachute parrot passport peanut pear peas pencil penguin piano pickup_truck picture_frame pig pillow pineapple pizza pliers police_car pond pool popsicle postcard potato power_outlet purse rabbit raccoon radio rain rainbow rake remote_control rhinoceros rifle river roller_coaster rollerskates sailboat sandwich saw saxophone school_bus scissors scorpion screwdriver sea_turtle see_saw shark sheep shoe shorts shovel sink skateboard skull skyscraper sleeping_bag smiley_face snail snake snorkel snowflake snowman soccer_ball sock speedboat spider spoon spreadsheet square squiggle squirrel stairs star steak stereo stethoscope stitches stop_sign stove strawberry streetlight string_bean submarine suitcase sun swan sweater swing_set sword syringe t-shirt table teapot teddy-bear telephone television tennis_racquet tent tiger toaster toe toilet tooth toothbrush toothpaste tornado tractor traffic_light train tree triangle trombone truck trumpet umbrella underwear van vase violin washing_machine watermelon waterslide whale wheel windmill wine_bottle wine_glass wristwatch yoga zebra zigzag
